global using BuildingBlocks.CQRS;
global using BasketAPI.Models;
global using BuildingBlocks.Exceptions;
global using Marten;
global using Carter;
global using Mapster;
global using MediatR;
global using FluentValidation;
global using BuildingBlocks.Behaviours;