services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalogDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/