services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile
  basket.api:
    image: basketapi
    build:
      context: .
      dockerfile: Services/Basket/BasketAPI/Dockerfile
  discount.grpc:
    image: discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
volumes:
  postgres_catalog: 
  postgres_basket: 
 