services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  messagebroker:
    image: rabbitmq:3-management
  catalog.api:
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile
  basket.api:
    build:
      context: .
      dockerfile: Services/Basket/BasketAPI/Dockerfile
  discount.grpc:
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
  ordering.api:
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
volumes:
  postgres_catalog: 
  postgres_basket: 
