services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile
volumes:
  postgres_catalog: 
  postgres_basket: 
 
